name: data-sharing-bw-jobs
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      text: ${{steps.nameid.outputs.msg}}
    steps:
      - name: generating output
        id: nameid
        run: echo "::set-output name=msg::msg from first job"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: "displaying output"
        run: echo ${{needs.job1.outputs.text}}
