name: "hello"
on: [push]
jobs:
  if-Windows-else:
    runs-on: macos-latest
    steps:
      - name: condition 1
        if: runner.os == 'Windows'
        run: echo "The operating system on the runner is $env:RUNNER_OS."
      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16"]
    env:
      os: runner.os
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setting node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: "checking os"
        if: env.os == Linux
        run: echo "You are in linux image"
