name: "hello"
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16"]
    env:
      os: runner.os
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setting node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: "checking os"
        if: env.os == Linux
        run: echo "You are in linux image"
